mail_subject: "Thông báo thu hồi laptop của #{full_name} - #{agent_code}"

is_template: True

mail_content:
  template-path: C:\Users\nmhil\Desktop\tmp2\20221231__template_content.msg
  encoding: utf-8